'''name = "kamakshi gupta "
age = 21
PI = 3.14
print(name,age,PI)

a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

a=10
b=20
print("a==b",a==b)
print("a!=b:",a!=b)
print("a>b:",a>b)
print("a<=b:",a<=b)
print("a<=b:",a<=b)

x=10
print("x+=5",x)
name=input("enter name:")
print(name)
print(type (name))

a=int(input("enter 1st num:"))
b=int(input("enter 2nd num:"))
avg=(a+b)/2
print("average=",avg)
'''

# write a program that asks the user for their name and age , then prints a sentence like
#Hello kamakshi, you are 21 years old !
name=input("enter name:")
age=input("enter age:")
print(name)
print (age)

name=input("enter name:")
age=input("enter age:")
print("Hello", name + ", you are", age, "years old")
'''

#Take two number as input from the user and print their.
#sum,difference,product,and quotient
a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a%b)

#Ask the user toenter two integers and one float.Convert them all to floats and print 
# the iraverage
# Ask the user to enter two integers and one float

num1 = float(int(input("Enter first integer: ")))
num2 = float(int(input("Enter second integer: ")))
num3 = float(input("Enter a float number: "))

average = (num1 + num2 + num3) / 3

print("Average =", average)
'''